# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

POST http://localhost:8081/actuator/refresh

###

POST http://localhost:8080/functional/customer
Content-Type: application/json

{ "id" : 18, "name" : "New Customer", "telephone" :  {"countryCode" :  "+44", "telephoneNumber" :  "1234"}}

###

DELETE http://localhost:8080/functional/customer/18

###

PUT http://localhost:8080/customer/2
Cache-Control: no-cache
Content-Type: application/json

{ "id" : 4, "name" : "Update Customer" }

###


GET http://localhost:8080/customer/12
Content-Type: application/json

{ "id" : 4, "name" : "New Customer" }

###