server:
  port: 8081

spring:
  application:
    name: "greetings"
  data:
    mongodb:
      uri: "mongodb://localhost:27700"
      database: "microservices"
  profiles:
    active: "development"
  jackson:
    default-property-inclusion: non_null

eureka:
  client:
    healthcheck:
      enabled: true

service:
  message:
    type: "simple"
    text: "hello"


---

spring:
  profiles: "development"


service:
  message:
    text: "hi"

---

spring:
  profiles: "production"

service:
  message:
    type: "advance"
    text: "welcome"